[package]
name = "backend"
version = "0.1.0"
authors = ["Joword <joword@my.swjtu.edu.cn>"]
edition = "2021"
rust-version = "1.75"
readme = "../README.md"
publish = false
keywords = ['middle platform', 'AI', 'medic']
licence = "Apache 2.0"
build = "build.rs"
exclude = ['icons/*']
repository = "https://github.com/Joword/demo-rust"
description = "a medic AI of platform as a service"

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
custom-protocol = ["tauri/custom-protocol"]
